#!/usr/bin/env node
/**
 * backup-remote.mjs — Backup a remote PostgreSQL database (e.g. Render)
 * without pg_dump. Uses the `pg` driver that ships with the project.
 *
 * Usage:
 *   node scripts/backup-remote.mjs                         # reads DATABASE_URL from server/.env
 *   DATABASE_URL=postgresql://... node scripts/backup-remote.mjs
 *   BACKUP_DIR=/custom/path node scripts/backup-remote.mjs
 *
 * Output: BACKUP_DIR/db/remote-postgres-YYYYMMDD-HHMM.sql.gz
 */

import { readFileSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import path from 'node:path';
import { createGzip } from 'node:zlib';
import { Pool } from 'pg';

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

function loadDatabaseUrl() {
  if (process.env.DATABASE_URL) return process.env.DATABASE_URL;
  for (const file of [path.join('server', '.env'), path.join('server', '.env.local'), '.env', '.env.local']) {
    try {
      const m = readFileSync(file, 'utf8').match(/^DATABASE_URL\s*=\s*(.+)$/m);
      if (m) return m[1].trim().replace(/^["']|["']$/g, '');
    } catch { /* skip */ }
  }
  return null;
}

const DATABASE_URL = loadDatabaseUrl();
if (!DATABASE_URL) {
  console.error('ERROR: No DATABASE_URL found. Set it in the environment or in server/.env');
  process.exit(1);
}

const BACKUP_DIR = process.env.BACKUP_DIR || path.join(homedir(), 'OneDrive', 'PizzaBackups');
const stamp = () => {
  const d = new Date();
  return `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}-${String(d.getHours()).padStart(2, '0')}${String(d.getMinutes()).padStart(2, '0')}`;
};
const dbDir = path.join(BACKUP_DIR, 'db');
mkdirSync(dbDir, { recursive: true });
const archivePath = path.join(dbDir, `remote-postgres-${stamp()}.sql.gz`);

// ---------------------------------------------------------------------------
// Tables — ordered to respect foreign keys
// ---------------------------------------------------------------------------

const TABLES = [
  'roles', 'permissions', 'users', 'categories', 'products',
  'product_sizes', 'product_extras', 'carts', 'cart_items',
  'orders', 'order_items', 'reviews', 'coupons', 'coupon_redemptions',
  'offers', 'offer_products', 'banners', 'branches', 'delivery_zones',
  'settings', 'posts', 'contacts', 'newsletters', 'notifications',
  'wishlists', 'wishlist_items', 'analytics', 'activity_logs',
];

// ---------------------------------------------------------------------------
// Value formatting helpers
// ---------------------------------------------------------------------------

const esc = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE';
  if (typeof v === 'number') return String(v);
  return "'" + String(v).replace(/'/g, "''") + "'";
};

const classifyType = (udt, dt) => {
  if (dt === 'ARRAY') return 'array';
  if (udt === 'bool') return 'boolean';
  if (['int2', 'int4', 'int8'].includes(udt)) return 'integer';
  if (['float4', 'float8', 'numeric'].includes(udt)) return 'numeric';
  if (['json', 'jsonb'].includes(udt)) return 'jsonb';
  if (udt === 'date') return 'date';
  if (['timestamptz', 'timestamp'].includes(udt)) return 'timestamptz';
  return 'string';
};

const formatValue = (val, t) => {
  if (val === null || val === undefined) return 'NULL';
  if (t === 'boolean') return val ? 'TRUE' : 'FALSE';
  if (t === 'jsonb' || t === 'json') return "'" + (typeof val === 'string' ? val : JSON.stringify(val)).replace(/'/g, "''") + "'";
  if (t === 'array') return Array.isArray(val) && val.length ? `ARRAY[${val.map(esc).join(', ')}]` : "'{}'";
  if (t === 'numeric' || t === 'integer') { const n = Number(val); return Number.isFinite(n) ? String(n) : '0'; }
  if (t === 'timestamptz' || t === 'date') return esc(val instanceof Date ? val.toISOString() : String(val));
  return esc(val);
};

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const pool = new Pool({
  connectionString: DATABASE_URL,
  max: 1,
  connectionTimeoutMillis: 15_000,
  statement_timeout: 120_000,
});

try {
  console.log('Connecting to database...');
  const testRow = await pool.query('SELECT current_database() AS db, now() AS ts');
  console.log(`Connected to "${testRow.rows[0].db}" at ${testRow.rows[0].ts}`);

  const lines = [];
  const add = (s) => lines.push(s);

  add(`-- Frezzer El Balad — Remote PostgreSQL backup`);
  add(`-- Database: ${testRow.rows[0].db}`);
  add(`-- Timestamp: ${testRow.rows[0].ts}`);
  add(`-- Generated by: scripts/backup-remote.mjs`);
  add('');
  add('BEGIN;');
  add('');

  let totalRows = 0;

  for (const table of TABLES) {
    const colsRes = await pool.query(
      `SELECT column_name, data_type, udt_name FROM information_schema.columns
       WHERE table_name = $1 AND table_schema = 'public' ORDER BY ordinal_position`, [table],
    );
    if (!colsRes.rows.length) { console.log(`  ⏭  ${table} — not found`); continue; }

    const cols = colsRes.rows;
    const colNames = cols.map((c) => `"${c.column_name}"`);
    const colTypes = cols.map((c) => classifyType(c.udt_name, c.data_type));

    const dataRes = await pool.query(`SELECT * FROM "${table}" ORDER BY 1`);
    console.log(`  ✓  ${table} — ${dataRes.rows.length} row(s)`);
    totalRows += dataRes.rows.length;

    if (!dataRes.rows.length) continue;

    add(`-- Table: ${table} (${dataRes.rows.length} rows)`);
    add(`LOCK TABLE "${table}" IN ACCESS EXCLUSIVE MODE;`);
    for (const row of dataRes.rows) {
      const vals = cols.map((c, i) => formatValue(row[c.column_name], colTypes[i]));
      add(`INSERT INTO "${table}" (${colNames.join(', ')}) VALUES (${vals.join(', ')});`);
    }
    add('');
  }

  add('COMMIT;');
  add(`-- Total rows: ${totalRows}`);
  add(`-- Complete at: ${new Date().toISOString()}`);

  // Gzip and write
  const sql = lines.join('\n');
  await new Promise((resolve, reject) => {
    const gz = createGzip({ level: 9 });
    const bufs = [];
    gz.on('data', (c) => bufs.push(c));
    gz.on('end', () => { writeFileSync(archivePath, Buffer.concat(bufs)); resolve(); });
    gz.on('error', reject);
    gz.end(sql);
  });

  const sizeMB = (statSync(archivePath).size / 1024 / 1024).toFixed(2);
  console.log(`\n✅ Backup complete!`);
  console.log(`   Archive: ${archivePath}`);
  console.log(`   Size:    ${sizeMB} MB`);
  console.log(`   Rows:    ${totalRows} total`);
} catch (err) {
  console.error(`\n❌ Backup FAILED: ${err.message}`);
  if (err.code) console.error(`   PG code: ${err.code}`);
  process.exit(1);
} finally {
  await pool.end();
}
