import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { createGunzip } from 'node:zlib';

// ---------------------------------------------------------------------------
// Backup verification test
//
// Verifies that the gzipped SQL backup files are structurally valid and
// contain all expected tables. Runs against the actual backup files on disk
// (no database connection needed).
// ---------------------------------------------------------------------------

const BACKUP_DIR = path.resolve(import.meta.dirname, '..', '..', '..', 'backups', 'db');

// Fallback: check the OneDrive backup location used by backup-remote.mjs
const ONEDRIVE_BACKUP_DIR =
  process.platform === 'win32'
    ? path.join('C:', 'Users', 'my pc', 'OneDrive', 'PizzaBackups', 'db')
    : null;

/**
 * All tables that MUST be present in a complete backup.
 * Ordered by the restore dependency (same as restore-remote.mjs).
 */
const REQUIRED_TABLES = [
  'roles',
  'permissions',
  'users',
  'categories',
  'products',
  'product_sizes',
  'product_extras',
  'carts',
  'cart_items',
  'orders',
  'order_items',
  'reviews',
  'coupons',
  'coupon_redemptions',
  'offers',
  'offer_products',
  'banners',
  'branches',
  'delivery_zones',
  'settings',
  'posts',
  'contacts',
  'newsletters',
  'notifications',
  'wishlists',
  'wishlist_items',
  'analytics',
  'activity_logs',
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function findBackupDir(): string | null {
  // Check project-local backups
  try {
    const files = readdirSync(BACKUP_DIR).filter((f) => f.endsWith('.sql.gz'));
    if (files.length > 0) return BACKUP_DIR;
  } catch { /* dir doesn't exist */ }

  // Check OneDrive
  if (ONEDRIVE_BACKUP_DIR) {
    try {
      const files = readdirSync(ONEDRIVE_BACKUP_DIR).filter((f) => f.endsWith('.sql.gz'));
      if (files.length > 0) return ONEDRIVE_BACKUP_DIR;
    } catch { /* dir doesn't exist */ }
  }

  return null;
}

function findLatestBackup(dir: string): string | null {
  try {
    const files = readdirSync(dir)
      .filter((f) => f.endsWith('.sql.gz'))
      .sort()
      .reverse();
    return files.length > 0 ? path.join(dir, files[0]) : null;
  } catch {
    return null;
  }
}

async function decompress(filePath: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const gunzip = createGunzip();
    const stream = readFileSync(filePath);
    gunzip.on('data', (c: Buffer) => chunks.push(c));
    gunzip.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    gunzip.on('error', reject);
    gunzip.end(stream);
  });
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('backup file integrity', () => {
  const backupDir = findBackupDir();

  if (!backupDir) {
    it.skip('no backup directory found — skipping backup verification tests', () => {});
    return;
  }

  const latestBackup = findLatestBackup(backupDir);

  if (!latestBackup) {
    it.skip('no .sql.gz files found in backup directory — skipping', () => {});
    return;
  }

  const backupName = path.basename(latestBackup);

  describe(`latest backup: ${backupName}`, () => {
    let sql: string;

    it('file exists and is readable', () => {
      expect(() => readFileSync(latestBackup)).not.toThrow();
    });

    it('file is valid gzip', async () => {
      // If decompress succeeds, it's valid gzip
      sql = await decompress(latestBackup);
      expect(sql).toBeDefined();
      expect(typeof sql).toBe('string');
    });

    it('contains valid SQL header', () => {
      expect(sql).toContain('-- Frezzer El Balad');
      expect(sql).toContain('-- Generated by: scripts/backup-remote.mjs');
    });

    it('contains a transaction block', () => {
      expect(sql).toContain('BEGIN;');
      expect(sql).toContain('COMMIT;');
    });

    it('contains a row count footer', () => {
      expect(sql).toMatch(/-- Total rows: \d+/);
    });

    it('contains all required tables that have data', () => {
      // Tables with no rows in production won't have INSERT/LOCK in the backup.
      // Only verify tables that our backup script dumped (have INSERT or LOCK).
      const EMPTY_TABLES = new Set([
        'permissions', 'carts', 'cart_items', 'orders', 'order_items',
        'coupon_redemptions', 'offers', 'offer_products', 'contacts',
        'newsletters', 'wishlists', 'wishlist_items', 'analytics',
      ]);
      const missingWith: string[] = [];
      for (const table of REQUIRED_TABLES) {
        const hasInsert = sql.includes(`INTO "${table}"`);
        const hasLock = sql.includes(`LOCK TABLE "${table}"`);
        if (EMPTY_TABLES.has(table)) {
          // Empty tables are acceptable — just make sure the backup is valid
          if (!hasInsert && !hasLock) continue;
        }
        if (!hasInsert && !hasLock) {
          missingWith.push(table);
        }
      }
      expect(missingWith).toEqual([]);
    });

    it('has INSERT statements for critical business tables', () => {
      // These tables MUST have data for the app to function
      const criticalTables = ['roles', 'users', 'categories', 'products', 'settings'];

      for (const table of criticalTables) {
        const insertCount = (sql.match(new RegExp(`INTO "${table}"`, 'g')) || []).length;
        expect(insertCount, `Expected INSERT statements for ${table}`).toBeGreaterThan(0);
      }
    });

    it('has proper statement structure (no unclosed quotes)', () => {
      // Check that single quotes are balanced (simplified check)
      let inSingleQuote = false;
      let quoteCount = 0;
      for (let i = 0; i < sql.length; i++) {
        if (sql[i] === "'" && (i === 0 || sql[i - 1] !== '\\')) {
          quoteCount++;
          inSingleQuote = !inSingleQuote;
        }
      }
      // Even number of single quotes (all are closed or escaped)
      expect(quoteCount % 2).toBe(0);
    });

    it('contains product data with non-zero prices', () => {
      // Find INSERT statements for products and check basePrice > 0
      const productInserts = sql.match(/INSERT INTO "products" \(([^)]+)\) VALUES \(([^)]+)\)/g);
      if (productInserts && productInserts.length > 0) {
        for (const insert of productInserts) {
          // Extract the columns list and values
          const colsMatch = insert.match(/INSERT INTO "products" \(([^)]+)\)/);
          const valsMatch = insert.match(/VALUES \((.+)\)$/);
          if (colsMatch && valsMatch) {
            const cols = colsMatch[1].split(',').map((c) => c.trim().replace(/"/g, ''));
            const basePriceIdx = cols.indexOf('basePrice');
            if (basePriceIdx >= 0) {
              // Parse the values (naive but sufficient for our backup format)
              const vals = valsMatch[1].split(',').map((v) => v.trim());
              const priceStr = vals[basePriceIdx];
              const price = parseFloat(priceStr);
              // Prices should be valid numbers (0 is acceptable for legacy products
              // but should not be NaN)
              expect(price, `basePrice should be a valid number, got: ${priceStr}`).not.toBeNaN();
            }
          }
        }
      }
    });

    it('contains all product sizes and extras', () => {
      const sizeInserts = (sql.match(/INTO "product_sizes"/g) || []).length;
      const extraInserts = (sql.match(/INTO "product_extras"/g) || []).length;
      // Should have at least some sizes and extras (from our production data)
      expect(sizeInserts).toBeGreaterThan(0);
      expect(extraInserts).toBeGreaterThan(0);
    });

    it('settings table contains key configuration', () => {
      const settingsInserts = (sql.match(/INTO "settings"/g) || []).length;
      expect(settingsInserts, 'Settings table should have data').toBeGreaterThan(0);

      // Check for critical settings keys
      const criticalSettings = ['restaurantName', 'deliveryFee', 'minimumOrder'];
      for (const key of criticalSettings) {
        expect(sql).toContain(key);
      }
    });
  });

  describe('all remote backup files', () => {
    it('every remote-postgres-*.sql.gz file is valid gzipped SQL', async () => {
      const files = readdirSync(backupDir)
        .filter((f) => f.startsWith('remote-postgres-') && f.endsWith('.sql.gz'));
      expect(files.length).toBeGreaterThan(0);

      for (const file of files) {
        const filePath = path.join(backupDir, file);
        const content = await decompress(filePath);
        expect(content, `${file} should decompress to valid SQL`).toBeDefined();
        expect(content, `${file} should contain BEGIN`).toContain('BEGIN;');
        expect(content, `${file} should contain COMMIT`).toContain('COMMIT;');
        expect(content, `${file} should contain Frezzer header`).toContain('Frezzer El Balad');
      }
    });
  });
});
